=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_CodeReview/Students.dtd
<!ELEMENT Students (student+)>
<!ELEMENT student (name, age, info)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ATTLIST student id CDATA #REQUIRED>

=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_CodeReview/Students1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--这是一行注释-->
<!DOCTYPE Students SYSTEM "Students.dtd">
<Students>
    <student id="01">
        <name>啦啦啦</name>
        <age>0</age>
        <info>叽里呱啦&lt;&gt;&amp;&apos;&quot;</info>

    </student>

    <student id="02">
        <name>嘟嘟嘟</name>
        <age>5</age>
        <info>叽里呱啦&lt;&gt;&amp;&apos;&quot;</info>

    </student>
</Students>
