=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_CodeReview/Students.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema
    xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="000000"
    elementFormDefault="qualified"
>
    <element name="Students">
        <complexType>
            <sequence>
                <element name="student" maxOccurs="10">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"></element>
                            <element name="age" type="string"></element>
                            <element name="info" type="string"></element>
                        </sequence>
                        <attribute name="id" type="string" use="required"></attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_Code/Students2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--注释一下-->
<Students
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="123456"
        xsi:schemaLocation="123456 Students.xsd"
>
    <student id="01">
        <name>啦啦啦</name>
        <age>0</age>
        <message></message>
        <info>学生&lt;&gt;&amp;&apos;&quot;</info>
    </student>

    <student id="02">
        <name>滴滴滴</name>
        <age>1</age>
        <message>
            <![CDATA[啦啦啦噜噜噜<<<>>>>>><<<]]>
        </message>
        <info>
            <![CDATA[
                哈哈哈哈哈哈
            ]]>
        </info>
    </student>

</Students>

=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_CodeReview/Students2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--这是一行注释-->

<Students
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="000000"
    xsi:schemaLocation="000000 Students.xsd"
>
    <student id="01">
        <name>啦啦啦</name>
        <age>0</age>
        <info>叽里呱啦&lt;&gt;&amp;&apos;&quot;</info>

    </student>

    <student id="02">
        <name>嘟嘟嘟</name>
        <age>5</age>
        <info>叽里呱啦&lt;&gt;&amp;&apos;&quot;</info>

    </student>
</Students>
