=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_Code/Students.dtd
<!ELEMENT Students (student+)>
        <!ELEMENT student (name, age, message, info)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT info (#PCDATA)>
        <!ELEMENT message (#PCDATA)>
        <!ATTLIST student id CDATA #REQUIRED>

=== cuichacha/Java_Learning_In_Heima/就业班JavaSE/src/Day17/xml_Code/Students1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students SYSTEM 'Students.dtd'>
<!--注释一下-->
<Students>
    <student id="01">
        <name>啦啦啦</name>
        <age>0</age>
        <message></message>
        <info>学生&lt;&gt;&amp;&apos;&quot;</info>
    </student>

    <student id="02">
        <name>滴滴滴</name>
        <age>1</age>
        <message>
            <![CDATA[啦啦啦噜噜噜<<<>>>>>><<<]]>
        </message>
        <info>
            <![CDATA[
                哈哈哈哈哈哈
            ]]>
        </info>
    </student>

</Students>
